### PR TITLE
Feature/pull in action mailer deliver methods

### LINKED ISSUE #1: deliver_later method
Hello! Thank you for this! I just have a question: is it possible to use the new deliver_later method to automatically send emails through ActiveJob?

Thanks again!

### PR DESCRIPTION
**Pull request by JuanitoFatas**
- Add message_delivery for Rails >= 4.0 & < 4.2.
- Sync Active Job with rails master.
- Sync globalid with https://github.com/rails/globalid.
- Test against more rubies and Active Support 4.1.x.

Attempt to fix #1.

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
- [x] Fix failures & errors on Rails 4.0.x.

**Comment by JuanitoFatas** [comment]
oh will try on weekend. Advices welcome!!! :smile:

**Comment by ankane** [comment]
Awesome, message delivery would be great.  From what I remember, a few things needing changed for Rails 4.0 were:
- can't use a block with `mattr_accessor` (silently ignored) - `mattr_accessor(:default_queue_name) { "default" }`
- can't support signed global ids

**Comment by JuanitoFatas** [comment]
Please see #3.

**Pull request closed without merging**
